### ISSUE TITLE
sprint create bug

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/ki-rally-manager#38]
I tried creating a sprint -- and it mostly worked -- but there was an exception thrown.
```
rallymanager --synapse_config ~/.synapseConfig_sage_ki_service --config ~/rally_config.json create-sprint 30 A
```

```
    INFO:kirallymanager.manager:Creating a new sprint 30A
INFO:kirallymanager.manager:Created sprint project syn22000247
Downloading  [####################]100.00%   358.0bytes/358.0bytes (952.2kB/s) masterTemplate.md Done...
    INFO:kirallymanager.manager:Set sprint project wiki.
INFO:kirallymanager.manager:Created sprint project folder structure.
INFO:kirallymanager.manager:Created sprint project forum posts.
Traceback (most recent call last):
  File "/Users/psnyder/Documents/virtual_environments/synapsepythonclient1.9.4/bin/rallymanager", line 120, in <module>
    main()
  File "/Users/psnyder/Documents/virtual_environments/synapsepythonclient1.9.4/bin/rallymanager", line 116, in main
    args.func(args)
  File "/Users/psnyder/Documents/virtual_environments/synapsepythonclient1.9.4/bin/rallymanager", line 26, in create_sprint
    config=config)
  File "/Users/psnyder/Documents/virtual_environments/synapsepythonclient1.9.4/lib/python3.7/site-packages/kirallymanager/manager.py", line 492, in create_sprint
    rally_admin_sprint_table = syn.store(rally_admin_sprint_table)
  File "/Users/psnyder/Documents/virtual_environments/synapsepythonclient1.9.4/lib/python3.7/site-packages/synapseclient/client.py", line 997, in store
    properties = self._updateEntity(properties, forceVersion, versionLabel)
  File "/Users/psnyder/Documents/virtual_environments/synapsepythonclient1.9.4/lib/python3.7/site-packages/synapseclient/client.py", line 3370, in _updateEntity
    return self.restPUT(uri, body=json.dumps(get_properties(entity)))
  File "/Users/psnyder/Documents/virtual_environments/synapsepythonclient1.9.4/lib/python3.7/site-packages/synapseclient/client.py", line 3490, in restPUT
    exceptions._raise_for_status(response, verbose=self.debug)
  File "/Users/psnyder/Documents/virtual_environments/synapsepythonclient1.9.4/lib/python3.7/site-packages/synapseclient/exceptions.py", line 153, in _raise_for_status
    raise SynapseHTTPError(message, response=response)
synapseclient.exceptions.SynapseHTTPError: 403 Client Error: 
You do not have UPDATE permission for the requested entity.
```

**Comment by kdaily** [comment]
`sage-ki-service` didn't have permissions to the file views. I fixed that.
